import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import React from "react";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { Providers } from "./providers";

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400", "500", "600"] 
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: { locale: "es" | "en" };
};

const RootLayout: React.FC<Props> = ({ children, params: { locale } }) => {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
